### ISSUE TITLE
[enhancement]flags

### ISSUE THREAD

**Issue by huzpsb** [jingwenMC/jpacp#1]
Could you please add a automic flags-based sorting system?
It means letting players report those who are cheating with a REASON
Then filt out those who are being reported for SAME reason?
(for there's always someone report normal players with random tickets.

**Comment by jingwenMC** [comment]
Sorry I don't have much time working on this project.  
If you are a dev , You can clone it an issue a Pull Request to add it.
Thanks for your advice.
